sonar.projectKey=josueGomez27_ProyectoProgra
sonar.organization=josuegomez27

sonar.projectName=ProyectoProgra
sonar.projectVersion=1.0

sonar.sources=turismolocal/src/main/java,turismo-local-frontend/src
sonar.tests=turismolocal/src/test/java

sonar.java.binaries=turismolocal/target/classes
sonar.coverage.jacoco.xmlReportPaths=turismolocal/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.idea/**,**/*.test.jsx,**/*.test.js
sonar.test.inclusions=**/*Test.java

sonar.sourceEncoding=UTF-8