sonar.projectKey=josuegomez27
sonar.organization=josueGomez27

# Servidor de SonarCloud
sonar.host.url=https://sonarcloud.io

# Código fuente que SonarCloud debe analizar
sonar.sources=turismo-local-frontend/src,turismolocal/src/main/java

# Carpeta de pruebas del backend
sonar.tests=turismolocal/src/test/java

# Archivos que no queremos analizar
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.github/**,turismo-local-frontend/src/**/*.test.*,turismo-local-frontend/src/**/*.spec.*

# Archivos de pruebas
sonar.test.inclusions=turismolocal/src/test/**/*.java

# Binarios compilados de Java
sonar.java.binaries=turismolocal/target/classes

# Reporte de cobertura del backend con JaCoCo
sonar.coverage.jacoco.xmlReportPaths=turismolocal/target/site/jacoco/jacoco.xml

# Reporte de cobertura del frontend, si existe
sonar.javascript.lcov.reportPaths=turismo-local-frontend/coverage/lcov.info

# Hace que el pipeline espere el resultado del Quality Gate
# Si el Quality Gate falla, el check queda en rojo
sonar.qualitygate.wait=true