server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: turismo_local

  datasource:
    url: jdbc:mysql://localhost:3306/turismo_local_db?useSSL=false&serverTimezone=America/Costa_Rica&allowPublicKeyRetrieval=true
    username: root
    password: Adrian123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1036381922111-0s9t8q5qalhab0n7burp39uv1jahiqjt.apps.googleusercontent.com

            client-secret: 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
            scope:
              - openid
              - email
              - profile
            client-name: Cliente web 1
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"