server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: turismo_local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            client-name: Cliente web 1
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"